# Generated by Django 5.0.6 on 2024-06-08 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('neighbor_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('signup_datetime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('_is_staff', models.BooleanField(default=False)),
                ('neighborhood', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.neighborhood')),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Addresse',
            fields=[
                ('address_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=27)),
                ('state', models.CharField(max_length=35)),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.neighborhood')),
            ],
        ),
    ]
