# Generated by Django 5.0.6 on 2024-06-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0002_rename__is_staff_neighbor_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
