# Generated by Django 5.0.6 on 2024-06-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0005_remove_neighbor_has_module_perms_neighbor_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='is_superuser',
        ),
    ]
