# Generated by Django 5.0.6 on 2024-06-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0006_remove_neighbor_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
