# Generated by Django 5.0.6 on 2024-06-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(default='Not assigned', max_length=255)),
                ('neighborhood_found_when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=27)),
                ('state', models.CharField(max_length=35)),
            ],
        ),
    ]
